//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.FE.Sites.Shop.Clothers.Projects.Web.Pages
{


    public partial class Contact
    {

        /// <summary>
        /// Top_Brands control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FE.Sites.Shop.Clothers.Projects.Web.Modules.Top_Brands Top_Brands;
    }
}
