//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.FrontEnds.Sites.MainPage.Projects.Homes.Home_Land.Controls
{


    public partial class Header
    {
    }
}
