//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Edu.Pages
{


    public partial class Land_Edu_Home
    {

        /// <summary>
        /// About_Us control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Edu.Modules.About_Us About_Us;

        /// <summary>
        /// Courses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Edu.Modules.Courses Courses;

        /// <summary>
        /// Demo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Edu.Modules.Demo Demo;

        /// <summary>
        /// Testimonials control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Edu.Modules.Testimonials Testimonials;

        /// <summary>
        /// Pricing control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Edu.Modules.Pricing Pricing;

        /// <summary>
        /// Team control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Edu.Modules.Team Team;

        /// <summary>
        /// Contact_Us control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Edu.Modules.Contact_Us Contact_Us;
    }
}
