//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.FrontEnds.Sites.MainPage.Projects.Blogspots.Video_Streaming.Pages
{


    public partial class Video_Streaming_Subcriptions
    {

        /// <summary>
        /// Channels control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Blogspots.Video_Streaming.Modules.Channels Channels;

        /// <summary>
        /// Channels1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Blogspots.Video_Streaming.Modules.Channels Channels1;

        /// <summary>
        /// Channels2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Blogspots.Video_Streaming.Modules.Channels Channels2;

        /// <summary>
        /// Channels3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Blogspots.Video_Streaming.Modules.Channels Channels3;
    }
}
