//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Contruction.Pages
{


    public partial class Land_Contruction_Home
    {

        /// <summary>
        /// About control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Contruction.Modules.About About;

        /// <summary>
        /// Services control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Contruction.Modules.Services Services;

        /// <summary>
        /// Portfolio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Contruction.Modules.Portfolio Portfolio;

        /// <summary>
        /// Testimonials control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Contruction.Modules.Testimonials Testimonials;

        /// <summary>
        /// Plans control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Contruction.Modules.Plans Plans;

        /// <summary>
        /// Contact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FrontEnds.Sites.MainPage.Projects.Landings.Landing_Contruction.Modules.Contact Contact;
    }
}
