//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Sites.Apps.Web.Controls.DashBoards.BoxType {
    
    
    public partial class BoxSmallYellow {
        
        /// <summary>
        /// boxSmall control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.Sites.Apps.Web.Controls.DashBoards.BoxType.BoxSmall boxSmall;
    }
}
