//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.FE.Sites.Api.Projects.Web.Pages
{


    public partial class Home
    {

        /// <summary>
        /// Features control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FE.Sites.Api.Projects.Web.Modules.Features Features;

        /// <summary>
        /// Videos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FE.Sites.Api.Projects.Web.Modules.Videos Videos;

        /// <summary>
        /// Screens control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FE.Sites.Api.Projects.Web.Modules.Screens Screens;

        /// <summary>
        /// Testimonials control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FE.Sites.Api.Projects.Web.Modules.Testimonials Testimonials;

        /// <summary>
        /// Pricing control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FE.Sites.Api.Projects.Web.Modules.Pricing Pricing;

        /// <summary>
        /// Team control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FE.Sites.Api.Projects.Web.Modules.Team Team;

        /// <summary>
        /// Comments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FE.Sites.Api.Projects.Web.Modules.Comments Comments;

        /// <summary>
        /// FreeTrial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Core.FE.Sites.Api.Projects.Web.Modules.FreeTrial FreeTrial;
    }
}
