//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.FE.Sites.Shop.Clothers.Projects.Web.Pages.Checkouts
{


    public partial class Step_Three
    {
    }
}
